name: Snyk Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  snyk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Dependencies
      run: npm install

    - name: Run Snyk Test and Save JSON
      run: snyk test --all-projects --json > snyk-results.json
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    - name: Notify Slack on Scan Completion
      run: |
        TEXT="✅ *Snyk Scan Completed* on \`${{ github.repository }}\` at branch \`${{ github.ref_name }}\`."
        curl -X POST -H 'Content-type: application/json' \
          --data "{\"text\":\"$TEXT\"}" \
          ${{ secrets.SLACK_WEBHOOK_URL }}
